export const  numbs = [
    {value: 7},
    {value: 8},
    {value: 9},
    {value: "DEL", btnType: "del"},
    {value: 4},
    {value: 5},
    {value: 6},
    {value: "+"},
    {value: 1},
    {value: 2},
    {value: 3},
    {value: "-"},
    {value: "."},
    {value: 0},
    {value: "/"},
    {value: "x"},
  ]
